CREATE TABLE IF NOT EXISTS `#__froala_profiles` (
`id` int(11) NOT NULL AUTO_INCREMENT,
  `title` varchar(200) NOT NULL,
  `description` varchar(250) NOT NULL,
  `ordering` int(11) NOT NULL,
  `published` int(2) NOT NULL,
  `default` tinyint(1) NOT NULL DEFAULT '0',
  `disable_right_click` tinyint(1) NOT NULL,
  `sanitize_url` tinyint(1) NOT NULL,
  `paragraphy` tinyint(1) NOT NULL,
  `plain_paste` tinyint(1) NOT NULL,
  `convert_urls` tinyint(1) NOT NULL,
  `resize_editor` tinyint(1) DEFAULT '0',
  `store_resize_height` tinyint(1) DEFAULT '0',
  `store_resize_days` int(5) DEFAULT '365',
  `images_load_url` text NOT NULL,
  `files_upload_url` text NOT NULL,
  `allow_media_manager` tinyint(1) NOT NULL,
  `allow_comments` tinyint(1) NOT NULL,
  `allow_script` tinyint(1) NOT NULL,
  `allow_style` tinyint(1) NOT NULL,
  `shortcuts` tinyint(1) NOT NULL,
  `allowed_attrs` text NOT NULL,
  `allowed_tags` text NOT NULL,
  `allowed_blank_tags` text NOT NULL,
  `max_file_size` int(10) NOT NULL,
  `max_image_size` int(10) NOT NULL,
  `paste_image` tinyint(1) NOT NULL,
  `image_upload` tinyint(1) NOT NULL,
  `image_delete` tinyint(1) NOT NULL,
  `file_upload` tinyint(1) NOT NULL,
  `allowed_image_types` text NOT NULL,
  `allowed_file_ext` text NOT NULL,
  `allowed_file_types` text NOT NULL,
  `buttons` text NOT NULL,
  `user_groups` text NOT NULL, 
   UNIQUE KEY `id` (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;

INSERT INTO `#__froala_profiles` (`id`, `title`, `description`, `ordering`, `published`, `default`, `paragraphy`, `plain_paste`, `convert_urls`, `images_load_url`, `files_upload_url`, `allow_media_manager`, `allow_comments`, `allow_script`, `allow_style`, `shortcuts`, `allowed_attrs`, `allowed_tags`, `allowed_blank_tags`, `max_file_size`, `max_image_size`, `paste_image`, `image_upload`, `allowed_image_types`, `allowed_file_ext`, `allowed_file_types`, `buttons`, `user_groups`, `disable_right_click`, `image_delete`, `file_upload`, `sanitize_url`) VALUES
  (1, 'Default', 'Default profile with the minimal permissions. This profile will be loaded to any user who does not have a different profile.', 0, 1, 1, 1, 1, 1, 'images/{userId}', 'images/{userId}', 0, 1, 0, 0, 0, '["title","href","alt","src","style"]', '', '', 2, 2, 0, 0, 'jpeg, jpg, png, gif', 'zip,doc,xls,xlsx,docx', 'image/jpeg,image/gif,image/png,image/bmp,application/x-shockwave-flash,application/msword,application/excel,application/pdf,application/powerpoint,text/plain,application/x-zip,application/zip,application/download,application/upload,application/x-zip-compressed', '["html","formatBlock","sep","bold","italic","underline","strikeThrough","sep","align","insertOrderedList","insertUnorderedList","sep","createLink","insertImage","insertVideo","sep","insertHorizontalRule","removeFormat","sep","fullscreen"]', '[]', 1, 0, 0,1),
  (2, 'Allow All', 'Allowed all permissions', 0, 1, 0, 1, 1, 1, 'images', 'images/{userId}', 1, 1, 1, 1, 1, '["*"]', '', '', 2, 2, 1, 1, 'jpeg, jpg, png, gif', 'zip,doc,xls,xlsx,docx', 'image/jpeg,image/gif,image/png,image/bmp,application/x-shockwave-flash,application/msword,application/excel,application/pdf,application/powerpoint,text/plain,application/x-zip,application/zip,application/download,application/upload,application/x-zip-compressed', '["html","blockStyle","inlineStyle","table","formatBlock","sep","bold","italic","underline","strikeThrough","subscript","superscript","fontFamily","fontSize","color","sep","align","insertOrderedList","insertUnorderedList","outdent","indent","sep","selectAll","createLink","insertImage","insertVideo","sep","undo","redo","sep","insertHorizontalRule","removeFormat","sep","uploadFile","fullscreen"]', '["8"]', 0, 1, 1,1),
  (3, 'Middle permissions', 'Middle permissions, for trusted users', 0, 1, 0, 1, 1, 1, 'images/{userId}', 'images/{userId}', 1, 1, 1, 1, 1, '["title","href","alt","src","style"]', '', '', 2, 2, 1, 1, 'jpeg, jpg, png, gif', 'zip,doc,xls,xlsx,docx', 'image/jpeg,image/gif,image/png,image/bmp,application/x-shockwave-flash,application/msword,application/excel,application/pdf,application/powerpoint,text/plain,application/x-zip,application/zip,application/download,application/upload,application/x-zip-compressed', '["html","formatBlock","table","blockStyle","inlineStyle","sep","bold","italic","underline","strikeThrough","subscript","superscript","sep","align","insertOrderedList","insertUnorderedList","sep","createLink","insertImage","insertVideo","sep","insertHorizontalRule","removeFormat","sep","fullscreen"]', '["6","7","3","4","5"]', 1, 0, 0,1);
